### ISSUE TITLE
Help interpreting project

### ISSUE THREAD

**Issue by Rocketscienceguy** [mrlem/kotlin-sample-game-template#1]

**Comment by mrlem** [comment]
Hi @Rocketscienceguy !

Indeed, in this template, SpringBoot targets only the server-side.

There's a reason for this: my goal is to retain Android compatibility, and SpringBoot is clearly not the way to go for dependency injection on this platform.

I think I did manage to run a SpringBoot+LibGDX app, which was desktop-only for the reason stated above. I might have lost the project since then. I'll check (but the link to your SO issue is 404, by the way).

**EDIT**
Just to confirm: I lost my LibGDX + client-side SpringBoot sample in a disk crash a few months ago, sorry :disappointed: 
I might try a rebuild a new one at some point (not sure how soon, though).

**Comment by Rocketscienceguy** [comment]
Thank you!  I appreciate your efforts here.  It was a long debug, but I eventually found I needed to add the databind dependency to my root build.gradle, and not just my /core version of that file.  Might just be my own inexperience with gradle at stake here than any unique shenanigans having to do with Spring.
